version: '3.1'

services:
  app:
    build: .
    image: takacsmark/flask-redis:1.0
    environment:
      - FLASK_ENV=development
    ports:
      - 5000:5000
    env_file: .secrets

  redis:
    image: redis:4.0.11-alpine

